# Classwork_1

## Exercise1

**Fill a 2-by-3 array with ones, a 3-by-3 array with zeros and a 2-
by-5 array with 7s.**

In [1]:
import numpy as np

In [2]:
arr1 = np.ones((2, 3))
arr2 = np.zeros((3, 3))
arr3 = np.empty((2, 5))
arr3.fill(7)

In [3]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr3

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

## Exercise 2

**Create a 3-by-3 array containing the even integers from 2 through 18. 
Create a second 3-by-3 array containing the integers from 9
down to 1, then multiply the first array by the second.**

In [11]:
arr1 = np.array([x for x in np.arange(2, 19) if x%2 == 0]).reshape(3, 3)
arr1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Exercise 3

**Create a 2-by-5 array from an argument which is a list
of the two five-element lists `[2, 3, 5, 7, 11]` and `[13, 17, 19, 23, 29]`.**

In [12]:
arr2 = np.array([2, 3, 5, 7, 11]+[13, 17, 19, 23, 29]).reshape(2, 5)
arr2

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])

## Exercise 4 (Extra credit)

**Research in the NumPy documentation the array method astype, which converts an array’s elements to another type. Use linspace and reshape to create a 2-by-3 array with the values `1.1, 2.2, …, 6.6`. Then use astype to convert the array to an array of integers.**

In [15]:
arr3 = np.linspace(1.1, 6.6, 6).reshape(2, 3)
arr3.astype('int32')

array([[1, 2, 3],
       [4, 5, 6]])